### ISSUE TITLE
Basic (50/50) 2 column layout

### ISSUE THREAD

**Issue by gmclelland** [JohnAlbin/zen-grids#31]
Hi John, I just wanted to drop in and say thank you for making zen-grids!  I'm really enjoying it.

One thing that confused me when I was creating my layout is that a two column side by side layout wouldn't work.

For a 12 column grid I was doing the following:

``` css
.container{
  $zen-column-count: 12; // Set the total number of columns in the grid.
  $zen-gutter-width: 10px;
  @include zen-grid-container;
  width: 90%;
  margin: 0 auto;
}
.one {
  @include zen-grid-item(6, 1);
}

.two {
  @include zen-grid-item(6, 2);
}
```

later I realized I had to do the following to get it to work properly:

``` css
.container{
  $zen-column-count: 12; // Set the total number of columns in the grid.
  $zen-gutter-width: 10px;
  @include zen-grid-container;
  width: 90%;
  margin: 0 auto;
}
.one {
  @include zen-grid-item(6, 1);
}

.two {
  @include zen-grid-item(6, 1, right);
}
```

Can you briefly explain or document why this is, and in what situation you would need to do this?

Thanks again
